services: 
  backend: 
    container_name: "guesser-backend"
    build: ./backend/.
    ports: 
      - "2888:3000"

  frontend: 
    container_name: "guesser-frontend"
    build: ./frontend/.
    depends_on: 
      - backend
    ports: 
      - "8000:8000"
